# Generated by Django 2.1.2 on 2018-11-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='threshold',
            field=models.FloatField(),
        ),
    ]
