# Generated by Django 2.1.2 on 2018-11-11 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20181105_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='result',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
