# Generated by Django 2.1.2 on 2018-11-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181104_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='favorite_subjects',
            field=models.ManyToManyField(blank=True, to='study.Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='favorite_subjects',
            field=models.ManyToManyField(blank=True, to='study.Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tracked_groups',
            field=models.ManyToManyField(blank=True, to='users.Group'),
        ),
    ]
