# Generated by Django 2.1.2 on 2019-01-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181104_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='favorite_subjects',
            field=models.ManyToManyField(blank=True, to='study.Subsection'),
        ),
    ]
