# Generated by Django 2.1.2 on 2019-01-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190103_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='favorite_subjects',
            new_name='favourite_subjects',
        ),
    ]
