# Generated by Django 2.1.2 on 2018-11-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subsections',
            field=models.ManyToManyField(blank=True, to='study.Subsection'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='themes',
            field=models.ManyToManyField(blank=True, to='study.Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='articles',
            field=models.ManyToManyField(blank=True, to='tasks.Article'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='games',
            field=models.ManyToManyField(blank=True, to='tasks.Game'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='videos',
            field=models.ManyToManyField(blank=True, to='tasks.Video'),
        ),
    ]
