# Generated by Django 2.1.2 on 2018-11-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
        ('study', '0002_auto_20181104_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='root_comments',
            field=models.ManyToManyField(blank=True, to='social_network.Comment'),
        ),
    ]
